name: Auto Version Bump

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Get current version
        id: get_version
        run: echo "INITIAL_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          NEW_VERSION=$(node increment_version.cjs $INITIAL_VERSION "${{ github.event.head_commit.message }}")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: node update_version.js $NEW_VERSION

      - name: Commit version bump
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add package.json
          git commit -m "[Auto-update] Version updated to $NEW_VERSION" || echo "No changes to commit"
          git push https://${PAT}@github.com/${{ github.repository }}.git HEAD:main
